/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardRouteImport } from './routes/card'
import { Route as DetainedRouteImport } from './routes/detained'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const DetainedRoute = DetainedRouteImport.update({
  id: '/detained',
  path: '/detained',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/detained': typeof DetainedRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/rights': typeof RightsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/detained': typeof DetainedRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/rights': typeof RightsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/detained': typeof DetainedRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/rights': typeof RightsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card'
    | '/detained'
    | '/legal'
    | '/medical'
    | '/rights'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/detained'
    | '/legal'
    | '/medical'
    | '/rights'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/card'
    | '/detained'
    | '/legal'
    | '/medical'
    | '/rights'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardRoute: typeof CardRoute
  DetainedRoute: typeof DetainedRoute
  LegalRoute: typeof LegalRoute
  MedicalRoute: typeof MedicalRoute
  RightsRoute: typeof RightsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detained': {
      id: '/detained'
      path: '/detained'
      fullPath: '/detained'
      preLoaderRoute: typeof DetainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardRoute: CardRoute,
  DetainedRoute: DetainedRoute,
  LegalRoute: LegalRoute,
  MedicalRoute: MedicalRoute,
  RightsRoute: RightsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
