/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as DetainedRouteImport } from './routes/detained'
import { Route as IndexRouteImport } from './routes/index'

const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const DetainedRoute = DetainedRouteImport.update({
  id: '/detained',
  path: '/detained',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detained': typeof DetainedRoute
  '/rights': typeof RightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detained': typeof DetainedRoute
  '/rights': typeof RightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detained': typeof DetainedRoute
  '/rights': typeof RightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detained' | '/rights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detained' | '/rights'
  id: '__root__' | '/' | '/detained' | '/rights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetainedRoute: typeof DetainedRoute
  RightsRoute: typeof RightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detained': {
      id: '/detained'
      path: '/detained'
      fullPath: '/detained'
      preLoaderRoute: typeof DetainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetainedRoute: DetainedRoute,
  RightsRoute: RightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
